<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LinqKit" Version="1.2.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.17">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.17" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Function\" />
    <None Remove="Views\DataView\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="wwwroot\moment\locale\af.js" />
    <None Include="wwwroot\moment\locale\ar-dz.js" />
    <None Include="wwwroot\moment\locale\ar-kw.js" />
    <None Include="wwwroot\moment\locale\ar-ly.js" />
    <None Include="wwwroot\moment\locale\ar-ma.js" />
    <None Include="wwwroot\moment\locale\ar-sa.js" />
    <None Include="wwwroot\moment\locale\ar-tn.js" />
    <None Include="wwwroot\moment\locale\ar.js" />
    <None Include="wwwroot\moment\locale\az.js" />
    <None Include="wwwroot\moment\locale\be.js" />
    <None Include="wwwroot\moment\locale\bg.js" />
    <None Include="wwwroot\moment\locale\bm.js" />
    <None Include="wwwroot\moment\locale\bn.js" />
    <None Include="wwwroot\moment\locale\bo.js" />
    <None Include="wwwroot\moment\locale\br.js" />
    <None Include="wwwroot\moment\locale\bs.js" />
    <None Include="wwwroot\moment\locale\ca.js" />
    <None Include="wwwroot\moment\locale\cs.js" />
    <None Include="wwwroot\moment\locale\cv.js" />
    <None Include="wwwroot\moment\locale\cy.js" />
    <None Include="wwwroot\moment\locale\da.js" />
    <None Include="wwwroot\moment\locale\de-at.js" />
    <None Include="wwwroot\moment\locale\de-ch.js" />
    <None Include="wwwroot\moment\locale\de.js" />
    <None Include="wwwroot\moment\locale\dv.js" />
    <None Include="wwwroot\moment\locale\el.js" />
    <None Include="wwwroot\moment\locale\en-au.js" />
    <None Include="wwwroot\moment\locale\en-ca.js" />
    <None Include="wwwroot\moment\locale\en-gb.js" />
    <None Include="wwwroot\moment\locale\en-ie.js" />
    <None Include="wwwroot\moment\locale\en-il.js" />
    <None Include="wwwroot\moment\locale\en-nz.js" />
    <None Include="wwwroot\moment\locale\en-SG.js" />
    <None Include="wwwroot\moment\locale\eo.js" />
    <None Include="wwwroot\moment\locale\es-do.js" />
    <None Include="wwwroot\moment\locale\es-us.js" />
    <None Include="wwwroot\moment\locale\es.js" />
    <None Include="wwwroot\moment\locale\et.js" />
    <None Include="wwwroot\moment\locale\eu.js" />
    <None Include="wwwroot\moment\locale\fa.js" />
    <None Include="wwwroot\moment\locale\fi.js" />
    <None Include="wwwroot\moment\locale\fo.js" />
    <None Include="wwwroot\moment\locale\fr-ca.js" />
    <None Include="wwwroot\moment\locale\fr-ch.js" />
    <None Include="wwwroot\moment\locale\fr.js" />
    <None Include="wwwroot\moment\locale\fy.js" />
    <None Include="wwwroot\moment\locale\ga.js" />
    <None Include="wwwroot\moment\locale\gd.js" />
    <None Include="wwwroot\moment\locale\gl.js" />
    <None Include="wwwroot\moment\locale\gom-latn.js" />
    <None Include="wwwroot\moment\locale\gu.js" />
    <None Include="wwwroot\moment\locale\he.js" />
    <None Include="wwwroot\moment\locale\hi.js" />
    <None Include="wwwroot\moment\locale\hr.js" />
    <None Include="wwwroot\moment\locale\hu.js" />
    <None Include="wwwroot\moment\locale\hy-am.js" />
    <None Include="wwwroot\moment\locale\id.js" />
    <None Include="wwwroot\moment\locale\is.js" />
    <None Include="wwwroot\moment\locale\it-ch.js" />
    <None Include="wwwroot\moment\locale\it.js" />
    <None Include="wwwroot\moment\locale\ja.js" />
    <None Include="wwwroot\moment\locale\jv.js" />
    <None Include="wwwroot\moment\locale\ka.js" />
    <None Include="wwwroot\moment\locale\kk.js" />
    <None Include="wwwroot\moment\locale\km.js" />
    <None Include="wwwroot\moment\locale\kn.js" />
    <None Include="wwwroot\moment\locale\ko.js" />
    <None Include="wwwroot\moment\locale\ku.js" />
    <None Include="wwwroot\moment\locale\ky.js" />
    <None Include="wwwroot\moment\locale\lb.js" />
    <None Include="wwwroot\moment\locale\lo.js" />
    <None Include="wwwroot\moment\locale\lt.js" />
    <None Include="wwwroot\moment\locale\lv.js" />
    <None Include="wwwroot\moment\locale\me.js" />
    <None Include="wwwroot\moment\locale\mi.js" />
    <None Include="wwwroot\moment\locale\mk.js" />
    <None Include="wwwroot\moment\locale\ml.js" />
    <None Include="wwwroot\moment\locale\mn.js" />
    <None Include="wwwroot\moment\locale\mr.js" />
    <None Include="wwwroot\moment\locale\ms-my.js" />
    <None Include="wwwroot\moment\locale\ms.js" />
    <None Include="wwwroot\moment\locale\mt.js" />
    <None Include="wwwroot\moment\locale\my.js" />
    <None Include="wwwroot\moment\locale\nb.js" />
    <None Include="wwwroot\moment\locale\ne.js" />
    <None Include="wwwroot\moment\locale\nl-be.js" />
    <None Include="wwwroot\moment\locale\nl.js" />
    <None Include="wwwroot\moment\locale\nn.js" />
    <None Include="wwwroot\moment\locale\pa-in.js" />
    <None Include="wwwroot\moment\locale\pl.js" />
    <None Include="wwwroot\moment\locale\pt-br.js" />
    <None Include="wwwroot\moment\locale\pt.js" />
    <None Include="wwwroot\moment\locale\ro.js" />
    <None Include="wwwroot\moment\locale\ru.js" />
    <None Include="wwwroot\moment\locale\sd.js" />
    <None Include="wwwroot\moment\locale\se.js" />
    <None Include="wwwroot\moment\locale\si.js" />
    <None Include="wwwroot\moment\locale\sk.js" />
    <None Include="wwwroot\moment\locale\sl.js" />
    <None Include="wwwroot\moment\locale\sq.js" />
    <None Include="wwwroot\moment\locale\sr-cyrl.js" />
    <None Include="wwwroot\moment\locale\sr.js" />
    <None Include="wwwroot\moment\locale\ss.js" />
    <None Include="wwwroot\moment\locale\sv.js" />
    <None Include="wwwroot\moment\locale\sw.js" />
    <None Include="wwwroot\moment\locale\ta.js" />
    <None Include="wwwroot\moment\locale\te.js" />
    <None Include="wwwroot\moment\locale\tet.js" />
    <None Include="wwwroot\moment\locale\tg.js" />
    <None Include="wwwroot\moment\locale\th.js" />
    <None Include="wwwroot\moment\locale\tl-ph.js" />
    <None Include="wwwroot\moment\locale\tlh.js" />
    <None Include="wwwroot\moment\locale\tr.js" />
    <None Include="wwwroot\moment\locale\tzl.js" />
    <None Include="wwwroot\moment\locale\tzm-latn.js" />
    <None Include="wwwroot\moment\locale\tzm.js" />
    <None Include="wwwroot\moment\locale\ug-cn.js" />
    <None Include="wwwroot\moment\locale\uk.js" />
    <None Include="wwwroot\moment\locale\ur.js" />
    <None Include="wwwroot\moment\locale\uz-latn.js" />
    <None Include="wwwroot\moment\locale\uz.js" />
    <None Include="wwwroot\moment\locale\vi.js" />
    <None Include="wwwroot\moment\locale\x-pseudo.js" />
    <None Include="wwwroot\moment\locale\yo.js" />
    <None Include="wwwroot\moment\locale\zh-cn.js" />
    <None Include="wwwroot\moment\locale\zh-hk.js" />
    <None Include="wwwroot\moment\locale\zh-tw.js" />
    <None Include="wwwroot\moment\min\locales.js" />
    <None Include="wwwroot\moment\min\locales.min.js" />
    <None Include="wwwroot\moment\min\moment-with-locales.js" />
    <None Include="wwwroot\moment\min\moment-with-locales.min.js" />
    <None Include="wwwroot\moment\min\moment.min.js" />
    <None Include="wwwroot\moment\moment.js" />
    <None Include="wwwroot\moment\src\lib\create\check-overflow.js" />
    <None Include="wwwroot\moment\src\lib\create\date-from-array.js" />
    <None Include="wwwroot\moment\src\lib\create\from-anything.js" />
    <None Include="wwwroot\moment\src\lib\create\from-array.js" />
    <None Include="wwwroot\moment\src\lib\create\from-object.js" />
    <None Include="wwwroot\moment\src\lib\create\from-string-and-array.js" />
    <None Include="wwwroot\moment\src\lib\create\from-string-and-format.js" />
    <None Include="wwwroot\moment\src\lib\create\from-string.js" />
    <None Include="wwwroot\moment\src\lib\create\local.js" />
    <None Include="wwwroot\moment\src\lib\create\parsing-flags.js" />
    <None Include="wwwroot\moment\src\lib\create\utc.js" />
    <None Include="wwwroot\moment\src\lib\create\valid.js" />
    <None Include="wwwroot\moment\src\lib\duration\abs.js" />
    <None Include="wwwroot\moment\src\lib\duration\add-subtract.js" />
    <None Include="wwwroot\moment\src\lib\duration\as.js" />
    <None Include="wwwroot\moment\src\lib\duration\bubble.js" />
    <None Include="wwwroot\moment\src\lib\duration\clone.js" />
    <None Include="wwwroot\moment\src\lib\duration\constructor.js" />
    <None Include="wwwroot\moment\src\lib\duration\create.js" />
    <None Include="wwwroot\moment\src\lib\duration\duration.js" />
    <None Include="wwwroot\moment\src\lib\duration\get.js" />
    <None Include="wwwroot\moment\src\lib\duration\humanize.js" />
    <None Include="wwwroot\moment\src\lib\duration\iso-string.js" />
    <None Include="wwwroot\moment\src\lib\duration\prototype.js" />
    <None Include="wwwroot\moment\src\lib\duration\valid.js" />
    <None Include="wwwroot\moment\src\lib\format\format.js" />
    <None Include="wwwroot\moment\src\lib\locale\base-config.js" />
    <None Include="wwwroot\moment\src\lib\locale\calendar.js" />
    <None Include="wwwroot\moment\src\lib\locale\constructor.js" />
    <None Include="wwwroot\moment\src\lib\locale\en.js" />
    <None Include="wwwroot\moment\src\lib\locale\formats.js" />
    <None Include="wwwroot\moment\src\lib\locale\invalid.js" />
    <None Include="wwwroot\moment\src\lib\locale\lists.js" />
    <None Include="wwwroot\moment\src\lib\locale\locale.js" />
    <None Include="wwwroot\moment\src\lib\locale\locales.js" />
    <None Include="wwwroot\moment\src\lib\locale\ordinal.js" />
    <None Include="wwwroot\moment\src\lib\locale\pre-post-format.js" />
    <None Include="wwwroot\moment\src\lib\locale\prototype.js" />
    <None Include="wwwroot\moment\src\lib\locale\relative.js" />
    <None Include="wwwroot\moment\src\lib\locale\set.js" />
    <None Include="wwwroot\moment\src\lib\moment\add-subtract.js" />
    <None Include="wwwroot\moment\src\lib\moment\calendar.js" />
    <None Include="wwwroot\moment\src\lib\moment\clone.js" />
    <None Include="wwwroot\moment\src\lib\moment\compare.js" />
    <None Include="wwwroot\moment\src\lib\moment\constructor.js" />
    <None Include="wwwroot\moment\src\lib\moment\creation-data.js" />
    <None Include="wwwroot\moment\src\lib\moment\diff.js" />
    <None Include="wwwroot\moment\src\lib\moment\format.js" />
    <None Include="wwwroot\moment\src\lib\moment\from.js" />
    <None Include="wwwroot\moment\src\lib\moment\get-set.js" />
    <None Include="wwwroot\moment\src\lib\moment\locale.js" />
    <None Include="wwwroot\moment\src\lib\moment\min-max.js" />
    <None Include="wwwroot\moment\src\lib\moment\moment.js" />
    <None Include="wwwroot\moment\src\lib\moment\now.js" />
    <None Include="wwwroot\moment\src\lib\moment\prototype.js" />
    <None Include="wwwroot\moment\src\lib\moment\start-end-of.js" />
    <None Include="wwwroot\moment\src\lib\moment\to-type.js" />
    <None Include="wwwroot\moment\src\lib\moment\to.js" />
    <None Include="wwwroot\moment\src\lib\moment\valid.js" />
    <None Include="wwwroot\moment\src\lib\parse\regex.js" />
    <None Include="wwwroot\moment\src\lib\parse\token.js" />
    <None Include="wwwroot\moment\src\lib\units\aliases.js" />
    <None Include="wwwroot\moment\src\lib\units\constants.js" />
    <None Include="wwwroot\moment\src\lib\units\day-of-month.js" />
    <None Include="wwwroot\moment\src\lib\units\day-of-week.js" />
    <None Include="wwwroot\moment\src\lib\units\day-of-year.js" />
    <None Include="wwwroot\moment\src\lib\units\hour.js" />
    <None Include="wwwroot\moment\src\lib\units\millisecond.js" />
    <None Include="wwwroot\moment\src\lib\units\minute.js" />
    <None Include="wwwroot\moment\src\lib\units\month.js" />
    <None Include="wwwroot\moment\src\lib\units\offset.js" />
    <None Include="wwwroot\moment\src\lib\units\priorities.js" />
    <None Include="wwwroot\moment\src\lib\units\quarter.js" />
    <None Include="wwwroot\moment\src\lib\units\second.js" />
    <None Include="wwwroot\moment\src\lib\units\timestamp.js" />
    <None Include="wwwroot\moment\src\lib\units\timezone.js" />
    <None Include="wwwroot\moment\src\lib\units\units.js" />
    <None Include="wwwroot\moment\src\lib\units\week-calendar-utils.js" />
    <None Include="wwwroot\moment\src\lib\units\week-year.js" />
    <None Include="wwwroot\moment\src\lib\units\week.js" />
    <None Include="wwwroot\moment\src\lib\units\year.js" />
    <None Include="wwwroot\moment\src\lib\utils\abs-ceil.js" />
    <None Include="wwwroot\moment\src\lib\utils\abs-floor.js" />
    <None Include="wwwroot\moment\src\lib\utils\abs-round.js" />
    <None Include="wwwroot\moment\src\lib\utils\compare-arrays.js" />
    <None Include="wwwroot\moment\src\lib\utils\defaults.js" />
    <None Include="wwwroot\moment\src\lib\utils\deprecate.js" />
    <None Include="wwwroot\moment\src\lib\utils\extend.js" />
    <None Include="wwwroot\moment\src\lib\utils\has-own-prop.js" />
    <None Include="wwwroot\moment\src\lib\utils\hooks.js" />
    <None Include="wwwroot\moment\src\lib\utils\index-of.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-array.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-date.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-function.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-number.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-object-empty.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-object.js" />
    <None Include="wwwroot\moment\src\lib\utils\is-undefined.js" />
    <None Include="wwwroot\moment\src\lib\utils\keys.js" />
    <None Include="wwwroot\moment\src\lib\utils\map.js" />
    <None Include="wwwroot\moment\src\lib\utils\mod.js" />
    <None Include="wwwroot\moment\src\lib\utils\some.js" />
    <None Include="wwwroot\moment\src\lib\utils\to-int.js" />
    <None Include="wwwroot\moment\src\lib\utils\zero-fill.js" />
    <None Include="wwwroot\moment\src\locale\af.js" />
    <None Include="wwwroot\moment\src\locale\ar-dz.js" />
    <None Include="wwwroot\moment\src\locale\ar-kw.js" />
    <None Include="wwwroot\moment\src\locale\ar-ly.js" />
    <None Include="wwwroot\moment\src\locale\ar-ma.js" />
    <None Include="wwwroot\moment\src\locale\ar-sa.js" />
    <None Include="wwwroot\moment\src\locale\ar-tn.js" />
    <None Include="wwwroot\moment\src\locale\ar.js" />
    <None Include="wwwroot\moment\src\locale\az.js" />
    <None Include="wwwroot\moment\src\locale\be.js" />
    <None Include="wwwroot\moment\src\locale\bg.js" />
    <None Include="wwwroot\moment\src\locale\bm.js" />
    <None Include="wwwroot\moment\src\locale\bn.js" />
    <None Include="wwwroot\moment\src\locale\bo.js" />
    <None Include="wwwroot\moment\src\locale\br.js" />
    <None Include="wwwroot\moment\src\locale\bs.js" />
    <None Include="wwwroot\moment\src\locale\ca.js" />
    <None Include="wwwroot\moment\src\locale\cs.js" />
    <None Include="wwwroot\moment\src\locale\cv.js" />
    <None Include="wwwroot\moment\src\locale\cy.js" />
    <None Include="wwwroot\moment\src\locale\da.js" />
    <None Include="wwwroot\moment\src\locale\de-at.js" />
    <None Include="wwwroot\moment\src\locale\de-ch.js" />
    <None Include="wwwroot\moment\src\locale\de.js" />
    <None Include="wwwroot\moment\src\locale\dv.js" />
    <None Include="wwwroot\moment\src\locale\el.js" />
    <None Include="wwwroot\moment\src\locale\en-au.js" />
    <None Include="wwwroot\moment\src\locale\en-ca.js" />
    <None Include="wwwroot\moment\src\locale\en-gb.js" />
    <None Include="wwwroot\moment\src\locale\en-ie.js" />
    <None Include="wwwroot\moment\src\locale\en-il.js" />
    <None Include="wwwroot\moment\src\locale\en-nz.js" />
    <None Include="wwwroot\moment\src\locale\en-SG.js" />
    <None Include="wwwroot\moment\src\locale\eo.js" />
    <None Include="wwwroot\moment\src\locale\es-do.js" />
    <None Include="wwwroot\moment\src\locale\es-us.js" />
    <None Include="wwwroot\moment\src\locale\es.js" />
    <None Include="wwwroot\moment\src\locale\et.js" />
    <None Include="wwwroot\moment\src\locale\eu.js" />
    <None Include="wwwroot\moment\src\locale\fa.js" />
    <None Include="wwwroot\moment\src\locale\fi.js" />
    <None Include="wwwroot\moment\src\locale\fo.js" />
    <None Include="wwwroot\moment\src\locale\fr-ca.js" />
    <None Include="wwwroot\moment\src\locale\fr-ch.js" />
    <None Include="wwwroot\moment\src\locale\fr.js" />
    <None Include="wwwroot\moment\src\locale\fy.js" />
    <None Include="wwwroot\moment\src\locale\ga.js" />
    <None Include="wwwroot\moment\src\locale\gd.js" />
    <None Include="wwwroot\moment\src\locale\gl.js" />
    <None Include="wwwroot\moment\src\locale\gom-latn.js" />
    <None Include="wwwroot\moment\src\locale\gu.js" />
    <None Include="wwwroot\moment\src\locale\he.js" />
    <None Include="wwwroot\moment\src\locale\hi.js" />
    <None Include="wwwroot\moment\src\locale\hr.js" />
    <None Include="wwwroot\moment\src\locale\hu.js" />
    <None Include="wwwroot\moment\src\locale\hy-am.js" />
    <None Include="wwwroot\moment\src\locale\id.js" />
    <None Include="wwwroot\moment\src\locale\is.js" />
    <None Include="wwwroot\moment\src\locale\it-ch.js" />
    <None Include="wwwroot\moment\src\locale\it.js" />
    <None Include="wwwroot\moment\src\locale\ja.js" />
    <None Include="wwwroot\moment\src\locale\jv.js" />
    <None Include="wwwroot\moment\src\locale\ka.js" />
    <None Include="wwwroot\moment\src\locale\kk.js" />
    <None Include="wwwroot\moment\src\locale\km.js" />
    <None Include="wwwroot\moment\src\locale\kn.js" />
    <None Include="wwwroot\moment\src\locale\ko.js" />
    <None Include="wwwroot\moment\src\locale\ku.js" />
    <None Include="wwwroot\moment\src\locale\ky.js" />
    <None Include="wwwroot\moment\src\locale\lb.js" />
    <None Include="wwwroot\moment\src\locale\lo.js" />
    <None Include="wwwroot\moment\src\locale\lt.js" />
    <None Include="wwwroot\moment\src\locale\lv.js" />
    <None Include="wwwroot\moment\src\locale\me.js" />
    <None Include="wwwroot\moment\src\locale\mi.js" />
    <None Include="wwwroot\moment\src\locale\mk.js" />
    <None Include="wwwroot\moment\src\locale\ml.js" />
    <None Include="wwwroot\moment\src\locale\mn.js" />
    <None Include="wwwroot\moment\src\locale\mr.js" />
    <None Include="wwwroot\moment\src\locale\ms-my.js" />
    <None Include="wwwroot\moment\src\locale\ms.js" />
    <None Include="wwwroot\moment\src\locale\mt.js" />
    <None Include="wwwroot\moment\src\locale\my.js" />
    <None Include="wwwroot\moment\src\locale\nb.js" />
    <None Include="wwwroot\moment\src\locale\ne.js" />
    <None Include="wwwroot\moment\src\locale\nl-be.js" />
    <None Include="wwwroot\moment\src\locale\nl.js" />
    <None Include="wwwroot\moment\src\locale\nn.js" />
    <None Include="wwwroot\moment\src\locale\pa-in.js" />
    <None Include="wwwroot\moment\src\locale\pl.js" />
    <None Include="wwwroot\moment\src\locale\pt-br.js" />
    <None Include="wwwroot\moment\src\locale\pt.js" />
    <None Include="wwwroot\moment\src\locale\ro.js" />
    <None Include="wwwroot\moment\src\locale\ru.js" />
    <None Include="wwwroot\moment\src\locale\sd.js" />
    <None Include="wwwroot\moment\src\locale\se.js" />
    <None Include="wwwroot\moment\src\locale\si.js" />
    <None Include="wwwroot\moment\src\locale\sk.js" />
    <None Include="wwwroot\moment\src\locale\sl.js" />
    <None Include="wwwroot\moment\src\locale\sq.js" />
    <None Include="wwwroot\moment\src\locale\sr-cyrl.js" />
    <None Include="wwwroot\moment\src\locale\sr.js" />
    <None Include="wwwroot\moment\src\locale\ss.js" />
    <None Include="wwwroot\moment\src\locale\sv.js" />
    <None Include="wwwroot\moment\src\locale\sw.js" />
    <None Include="wwwroot\moment\src\locale\ta.js" />
    <None Include="wwwroot\moment\src\locale\te.js" />
    <None Include="wwwroot\moment\src\locale\tet.js" />
    <None Include="wwwroot\moment\src\locale\tg.js" />
    <None Include="wwwroot\moment\src\locale\th.js" />
    <None Include="wwwroot\moment\src\locale\tl-ph.js" />
    <None Include="wwwroot\moment\src\locale\tlh.js" />
    <None Include="wwwroot\moment\src\locale\tr.js" />
    <None Include="wwwroot\moment\src\locale\tzl.js" />
    <None Include="wwwroot\moment\src\locale\tzm-latn.js" />
    <None Include="wwwroot\moment\src\locale\tzm.js" />
    <None Include="wwwroot\moment\src\locale\ug-cn.js" />
    <None Include="wwwroot\moment\src\locale\uk.js" />
    <None Include="wwwroot\moment\src\locale\ur.js" />
    <None Include="wwwroot\moment\src\locale\uz-latn.js" />
    <None Include="wwwroot\moment\src\locale\uz.js" />
    <None Include="wwwroot\moment\src\locale\vi.js" />
    <None Include="wwwroot\moment\src\locale\x-pseudo.js" />
    <None Include="wwwroot\moment\src\locale\yo.js" />
    <None Include="wwwroot\moment\src\locale\zh-cn.js" />
    <None Include="wwwroot\moment\src\locale\zh-hk.js" />
    <None Include="wwwroot\moment\src\locale\zh-tw.js" />
    <None Include="wwwroot\moment\src\moment.js" />
    <None Include="wwwroot\moment\templates\default.js" />
    <None Include="wwwroot\moment\templates\locale-header.js" />
    <None Include="wwwroot\moment\templates\test-header.js" />
    <None Include="wwwroot\Notiflix-1.9.1\AIO\notiflix-aio-1.9.1.js" />
    <None Include="wwwroot\Notiflix-1.9.1\AIO\notiflix-aio-1.9.1.min.js" />
    <None Include="wwwroot\Notiflix-1.9.1\Minified\notiflix-1.9.1.min.js" />
    <None Include="wwwroot\Notiflix-1.9.1\Unminified\notiflix-1.9.1.js" />
    <None Include="wwwroot\NotiflixNew\AIO\notiflix-aio-1.9.1.js" />
    <None Include="wwwroot\NotiflixNew\AIO\notiflix-aio-1.9.1.min.js" />
    <None Include="wwwroot\NotiflixNew\Minified\notiflix-1.9.1.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-block-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-confirm-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-loading-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-notify-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\notiflix-report-aio-3.2.4.min.js" />
    <None Include="wwwroot\NotiflixNew\Unminified\notiflix-1.9.1.js" />
  </ItemGroup>
</Project>
