// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Packing.Models;

public partial class tbm_plant
{
    public string PLANT { get; set; }

    public string PLANT_NAME { get; set; }

    public bool? ACTIVE { get; set; }

    public string CREATE_BY { get; set; }

    public DateTime? CREATE_DATE { get; set; }

    public string UPDATE_BY { get; set; }

    public DateTime? UPDATE_DATE { get; set; }
}