// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Packing.Models;

public partial class VMS_CORE_2Context : DbContext
{
    public VMS_CORE_2Context(DbContextOptions<VMS_CORE_2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<tbm_plant> tbm_plants { get; set; }

    public virtual DbSet<tbm_unit> tbm_units { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Thai_CI_AS");

        modelBuilder.Entity<tbm_plant>(entity =>
        {
            entity.HasKey(e => e.PLANT);

            entity.ToTable("tbm_plant");

            entity.Property(e => e.PLANT).HasMaxLength(1);
            entity.Property(e => e.CREATE_BY).HasMaxLength(10);
            entity.Property(e => e.CREATE_DATE).HasColumnType("datetime");
            entity.Property(e => e.PLANT_NAME).HasMaxLength(35);
            entity.Property(e => e.UPDATE_BY).HasMaxLength(10);
            entity.Property(e => e.UPDATE_DATE).HasColumnType("datetime");
        });

        modelBuilder.Entity<tbm_unit>(entity =>
        {
            entity.HasKey(e => e.UOM);

            entity.ToTable("tbm_unit");

            entity.Property(e => e.UOM).HasMaxLength(3);
            entity.Property(e => e.CREATE_BY).HasMaxLength(10);
            entity.Property(e => e.CREATE_DATE).HasColumnType("datetime");
            entity.Property(e => e.UOM_NAME).HasMaxLength(35);
            entity.Property(e => e.UPDATE_BY).HasMaxLength(10);
            entity.Property(e => e.UPDATE_DATE).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}